### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by Mikeysax** [cldambrosio/firehose-splurty#1]
On mobile things don't look as good as they could be.
One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.
Let me know in the comments once you figured that step out :)

**Comment by cldambrosio** [comment]
Hi Michael, thank you for pointing me in the right direction :) I found out more about that and now it looks better on mobile.

**Comment by Mikeysax** [comment]
Nice! Good job adding the mobile meta tag 👍
